name: CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest
    env:
      solution-directory: ./SByteDev.MvvmCross.Plugins.DateTimeConverter
      project-directory: SByteDev.MvvmCross.Plugins.DateTimeConverter

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore NuGet packages
      run: nuget restore
    - name: Build using MSBuild
      run: msbuild -p:Configuration=Release
    - name: Push to NuGet
      working-directory: ${{ env.solution-directory }}
      run: dotnet nuget push ${{ env.project-directory }}/bin/Release/*.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
