name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest
    env:
      SOLUTION_DIR: ./SByteDev.MvvmCross.Plugins.DateTimeConverter

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
    - name: Restore
      working-directory: ${{ env.SOLUTION_DIR }}
      run: dotnet restore
    - name: Build
      working-directory: ${{ env.SOLUTION_DIR }}
      run: msbuild -p:Configuration=Release
