name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: macos-latest
    env:
      SOLUTION_DIR: ./SByteDev.MvvmCross.Plugins.DateTimeConverter
      PROJECT_DIR: SByteDev.MvvmCross.Plugins.DateTimeConverter

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore NuGet packages
      working-directory: ${{ env.SOLUTION_DIR }}
      run: nuget restore
    - name: Build using MSBuild
      working-directory: ${{ env.SOLUTION_DIR }}
      run: msbuild -p:Configuration=Release
